#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# the "app_welcome_base" route name is not important yet
# app_welcome:
#     path: /welcome/number
#    controller: App\Controller\WelcomeController::number
logout:
    path: /logout
#    controller: App\Controller\SecurityController::logout

login-check:
    path: /login_check